name: Deploy para KingHost

on:
  push:
    branches:
      - main  # O deploy será disparado quando houver um push na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Configurar Acesso SSH
        uses: webfactory/ssh-agent@v0.5.3
        with: 
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Adicione sua chave SSH privada nos segredos do GitHub

      - name: Acessar o servidor via SSH e realizar o deploy
        run: |
          ssh -o StrictHostKeyChecking=no usuario@ftp.purpletechnology.com.br << 'EOF'
          cd www/app/

          # Clonar ou atualizar o repositório
          if [ -d ".git" ]; then
            git pull origin main
          else
            git clone https://github.com/fabmasouza/purple-core-frontend .
          fi

          # Instalar o Composer
          if [ ! -f "composer.phar" ]; then
            curl -sS https://getcomposer.org/installer | php
          fi

          # Instalar dependências otimizadas
          php composer.phar install --optimize-autoloader --no-dev

          # Verificar ou criar o arquivo .env
          if [ ! -f ".env" ]; then
            cp .env.example .env
          fi

          # Mover o conteúdo da pasta public para a raiz (caso necessário)
          rsync -av --progress public/ ../

          # Ajustar permissões
          chmod -R 755 storage
          chmod -R 755 bootstrap/cache

          # Gerar a chave de acesso
          php artisan key:generate

          EOF

      - name: Notificar sucesso
        run: echo "Deploy concluído com sucesso!"
