name: Deploy para KingHost

on:
  push:
    branches:
      - main  # O deploy será disparado quando houver um push na branch 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checar o código
        uses: actions/checkout@v2

      - name: Configurar Acesso SSH
        uses: webfactory/ssh-agent@v0.5.3
        with: 
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}  # Adicione sua chave SSH privada nos segredos do GitHub

      - name: Acessar o servidor via SSH e realizar o deploy
        run: |
          ssh -o StrictHostKeyChecking=no purpletechnology@ftp.purpletechnology.com.br << 'EOF'
          cd www/app/
          ls -l

          EOF

      - name: Notificar sucesso
        run: echo "Deploy concluído com sucesso!"
